language: python
python:
  - "2.7"
sudo: false
install:
- make develop
- pip install python-coveralls
script: make testcov
after_success:
- coveralls
notifications:
    irc:
        channels:
            - "irc.freenode.net#ideascube"
        on_success: change
        on_failure: always
    email: false
addons:
  apt:
    packages:
    - autoconf
    - automake
    - libdbus-glib-1-dev
    - libtool
