site_name: Ideastube
pages:
- [index.md, Home]
- [install.md, Installation]
- [config.md, Configuration]
- [i18n.md, Translations]
theme: yeti
repo_url: https://github.com/ideastube/ideastube
site_description: Ideas Box server core application.
