site_name: Ideascube
pages:
- [index.md, Home]
- [install.md, Installation]
- [config.md, Configuration]
- [contributing.md, Contributing]
- [i18n.md, Translations]
theme: yeti
repo_url: https://github.com/ideascube/ideascube
site_description: Ideas Box server core application.
